name: Google Cloud CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Build Docker image
      run: |
        gcloud auth configure-docker
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/scooters-app:latest .

    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/scooters-app:latest

  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy scooters-app --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/scooters-app:latest --platform managed --region europe-west1
